export const trucks = [
  {
    id: 1,
    number: "TRK001",
    status: "In Transit",
    capacity: "20 tons",
    driver: "Ravi Kumar",
  },
  {
    id: 2,
    number: "TRK002",
    status: "In Transit",
    capacity: "15 tons",
    driver: "Anil Sharma",
  },
  {
    id: 3,
    number: "TRK003",
    status: "In Transit",
    capacity: "25 tons",
    driver: "Suresh Patel",
  },
  {
    id: 4,
    number: "TRK004",
    status: "In Transit",
    capacity: "18 tons",
    driver: "Rajesh Yadav",
  },
  {
    id: 5,
    number: "TRK005",
    status: "Maintenance",
    capacity: "22 tons",
    driver: "Kumar Ghosh",
  },
  {
    id: 6,
    number: "TRK006",
    status: "Maintenance",
    capacity: "22 tons",
    driver: "Sunil Mehta",
  },
  {
    id: 7,
    number: "TRK007",
    status: "In Transit",
    capacity: "25 tons",
    driver: "Vikram Singh",
  },
];

export const drivers = [
  {
    id: 1,
    name: "Ravi Kumar",
    contact: "999-888-7777",
    truckAssigned: "TRK001",
  },
  {
    id: 2,
    name: "Anil Sharma",
    contact: "888-777-6666",
    truckAssigned: "TRK002",
  },
  {
    id: 3,
    name: "Suresh Patel",
    contact: "777-666-5555",
    truckAssigned: "TRK003",
  },
  {
    id: 4,
    name: "Rajesh Yadav",
    contact: "666-555-4444",
    truckAssigned: "TRK004",
  },
  {
    id: 5,
    name: "Kumar Ghosh",
    contact: "555-444-3333",
    truckAssigned: "TRK005",
  },
  {
    id: 6,
    name: "Sunil Mehta",
    contact: "444-333-2222",
    truckAssigned: "TRK006",
  },
];

export const vendors = [
  { id: 1, name: "Transport Co.", drivers: ["Ravi", "Suresh"] },
  { id: 2, name: "Logistics Ltd.", drivers: ["Anil", "Rajesh"] },
  { id: 3, name: "Freight Inc.", drivers: ["Sunil"] },
  { id: 4, name: "Haulage LLC", drivers: ["Vikram"] },
];

export const simulateTruckData = () => [
  {
    id: 1,
    name: "Truck 1",
    status: "In Transit",
    lat: 12.9716,
    lng: 77.5946,
    capacity: "20 tons",
    driver: "Ravi Kumar",
  },
  {
    id: 2,
    name: "Truck 2",
    status: "In Transit",
    lat: 13.0827,
    lng: 80.2707,
    capacity: "15 tons",
    driver: "Anil Sharma",
  },
  {
    id: 3,
    name: "Truck 3",
    status: "In Transit",
    lat: 28.6139,
    lng: 77.209,
    capacity: "25 tons",
    driver: "Suresh Patel",
  },
  {
    id: 4,
    name: "Truck 4",
    status: "In Transit",
    lat: 19.076,
    lng: 72.8777,
    capacity: "18 tons",
    driver: "Rajesh Yadav",
  },
  {
    id: 5,
    name: "Truck 5",
    status: "Maintenance",
    lat: 22.5726,
    lng: 88.3639,
    capacity: "22 tons",
    driver: "Kumar Ghosh",
  },
  {
    id: 6,
    name: "Truck 6",
    status: "Maintenance",
    lat: 17.385,
    lng: 78.4867,
    capacity: "22 tons",
    driver: "Sunil Mehta",
  },
  {
    id: 7,
    name: "Truck 7",
    status: "In Transit",
    lat: 27.1767,
    lng: 78.0081,
    capacity: "25 tons",
    driver: "Vikram Singh",
  },
  {
    id: 8,
    name: "Truck 8",
    status: "Maintenance",
    lat: 26.9124,
    lng: 75.7873,
    capacity: "5 tons",
    driver: "Manoj Kumar",
  },
];
