export const trucks = [
  {
    id: 1,
    number: "TRK001",
    status: "In Transit",
    capacity: "20 tons",
    driver: "Driver A",
  },
  {
    id: 2,
    number: "TRK002",
    status: "In Transit",
    capacity: "15 tons",
    driver: "Driver B",
  },
  {
    id: 3,
    number: "TRK003",
    status: "In Transit",
    capacity: "25 tons",
    driver: "Driver C",
  },
  {
    id: 4,
    number: "TRK004",
    status: "In Transit",
    capacity: "18 tons",
    driver: "Driver D",
  },
  {
    id: 5,
    number: "TRK005",
    status: "Maintenance",
    capacity: "22 tons",
    driver: "Driver E",
  },
  {
    id: 6,
    number: "TRK006",
    status: "Maintenance",
    capacity: "22 tons",
    driver: "Driver F",
  },
  {
    id: 7,
    number: "TRK007",
    status: "In Transit",
    capacity: "25 tons",
    driver: "Driver G",
  },
];

export const drivers = [
  { id: 1, name: "Driver A", contact: "123-456-7890", truckAssigned: "TRK001" },
  { id: 2, name: "Driver B", contact: "987-654-3210", truckAssigned: "TRK002" },
  { id: 3, name: "Driver C", contact: "111-222-3333", truckAssigned: "TRK003" },
  { id: 4, name: "Driver D", contact: "444-555-6666", truckAssigned: "TRK004" },
  { id: 5, name: "Driver E", contact: "777-888-9999", truckAssigned: "TRK005" },
  { id: 6, name: "Driver F", contact: "101-202-3030", truckAssigned: "TRK006" },
];

export const vendors = [
  { id: 1, name: "Vendor A", drivers: ["Driver A", "Driver B"] },
  { id: 2, name: "Vendor B", drivers: ["Driver C", "Driver D"] },
  { id: 3, name: "Vendor C", drivers: ["Driver E"] },
  { id: 4, name: "Vendor D", drivers: ["Driver F"] },
];

export const simulateTruckData = () => [
  {
    id: 1,
    name: "Truck 1",
    status: "In Transit",
    lat: 12.9716,
    lng: 77.5946,
    capacity: "20 tons",
    driver: "Driver A",
  },
  {
    id: 2,
    name: "Truck 2",
    status: "In Transit",
    lat: 13.0827,
    lng: 80.2707,
    capacity: "15 tons",
    driver: "Driver B",
  },
  {
    id: 3,
    name: "Truck 3",
    status: "In Transit",
    lat: 28.6139,
    lng: 77.209,
    capacity: "25 tons",
    driver: "Driver C",
  },
  {
    id: 4,
    name: "Truck 4",
    status: "In Transit",
    lat: 19.076,
    lng: 72.8777,
    capacity: "18 tons",
    driver: "Driver D",
  },
  {
    id: 5,
    name: "Truck 5",
    status: "Maintenance",
    lat: 22.5726,
    lng: 88.3639,
    capacity: "22 tons",
    driver: "Driver E",
  },
  {
    id: 6,
    name: "Truck 6",
    status: "Maintenance",
    lat: 17.385,
    lng: 78.4867,
    capacity: "22 tons",
    driver: "Driver F",
  },
  {
    id: 7,
    name: "Truck 7",
    status: "In Transit",
    lat: 27.1767,
    lng: 78.0081,
    capacity: "25 tons",
    driver: "Driver G",
  },
  {
    id: 8,
    name: "Truck 8",
    status: "Maintenance",
    lat: 26.9124,
    lng: 75.7873,
    capacity: "05 tons",
    driver: "Driver H",
  },
];
